import requests


def generate_template(word_for_template):
    x = requests.get("https://relatedwords.org/api/related?term=" + word_for_template)
    to_return = ""
    # Adding the first 10 words generated by Related Words
    for i in range(0, 10):
        to_return += (x.json()[i]["word"]) + "\n"
    return to_return


def write_template_file(name, text_content):
    text_file = open("output/" + name + ".txt", "w")
    text_file.write(text_content)
    text_file.close()


if __name__ == '__main__':
    word = input("Which word would you like to generate a template for? ")
    print("Ok! Generating a template for " + word + "...")
    template = generate_template(word)
    write_template_file(word, template)
    print("I have written the following template to " + word + ".txt:\n" + template)
